export const PRODUCTS = {
  'barn-door-hardware': [
    {
      slug: 'gainesville',
      name: 'Gainesville',
      type: 'Single Sliding',
      price: 150,
      fromPrice: true,
      headroom: '175mm',
      trackNote: 'Track = 2× door width',
      description: 'The Gainesville is our most popular single sliding barn door hardware kit. UK manufactured in Cardiff, this system requires 175mm of headroom and uses a track twice the width of your door. Supplied complete with all fixings.',
      features: [
        'UK manufactured in Cardiff',
        'Headroom required: 175mm',
        'Track length: 2× door width',
        'Suitable for single doors',
        'All fixings included',
        'Soft close available separately',
      ],
      image: '/img/gainesville.png',
      images: ['/img/gainesville.png', '/img/gainesville-2.png', '/img/gainesville-closeup.png'],
      buyLink: 'https://www.barn-doors.co.uk/?Page_ID=3610&id=754330',
      badge: 'BEST SELLER',
      category: 'barn-door-hardware',
      metaTitle: 'Gainesville Barn Door Hardware Kit | From £150 | DoorMate Cardiff',
      metaDesc: 'The Gainesville single sliding barn door hardware kit. UK manufactured in Cardiff. 175mm headroom, track = 2× door width. From £150. Order direct from DoorMate.',
    },
    {
      slug: 'detroit',
      name: 'Detroit',
      type: 'Single LOW HEADROOM',
      price: 150,
      fromPrice: true,
      headroom: 'Standard 130mm / Reversed 90mm',
      trackNote: 'Low headroom system',
      description: 'The Detroit is our single sliding low headroom barn door hardware kit. Perfect for rooms where ceiling height is restricted. Available in standard (130mm) or reversed (90mm) configurations. UK manufactured in Cardiff.',
      features: [
        'UK manufactured in Cardiff',
        'Standard headroom: 130mm',
        'Reversed headroom: 90mm',
        'Single door system',
        'Ideal for restricted ceiling heights',
        'All fixings included',
      ],
      image: '/img/detroit-system.jpg',
      images: ['/img/detroit-system.jpg'],
      buyLink: 'https://www.barn-doors.co.uk/?Page_ID=3610&id=824243',
      badge: 'LOW HEADROOM',
      category: 'barn-door-hardware',
      metaTitle: 'Detroit Low Headroom Barn Door Hardware | From £150 | DoorMate',
      metaDesc: 'Detroit single low headroom barn door kit. Standard 130mm or reversed 90mm. UK manufactured in Cardiff. From £150. Perfect for tight ceiling spaces.',
    },
    {
      slug: 'brooklyn',
      name: 'Brooklyn',
      type: 'Double Bi-Parting',
      price: 290,
      fromPrice: true,
      headroom: '175mm',
      trackNote: 'Track = 4× door width — doors slide APART',
      description: 'The Brooklyn is our double bi-parting barn door hardware kit. Both doors slide away from the centre opening — ideal for wide doorways. Requires a track four times the width of a single door. UK manufactured in Cardiff.',
      features: [
        'UK manufactured in Cardiff',
        'Bi-parting — doors slide apart from centre',
        'Headroom required: 175mm',
        'Track length: 4× single door width',
        'Suits wide openings',
        'All fixings included',
      ],
      image: '/img/brooklyn-system.jpg',
      images: ['/img/brooklyn-system.jpg', '/img/brooklyn-system-2.jpg'],
      buyLink: 'https://www.barn-doors.co.uk/?Page_ID=3610&id=754348',
      badge: 'BI-PARTING',
      category: 'barn-door-hardware',
      metaTitle: 'Brooklyn Double Bi-Parting Barn Door Hardware | From £290 | DoorMate',
      metaDesc: 'Brooklyn double bi-parting barn door hardware. Doors slide apart from centre. 175mm headroom, track = 4× door width. UK made. From £290.',
    },
    {
      slug: 'baltimore',
      name: 'Baltimore',
      type: 'Double Bi-Parting LOW HEADROOM',
      price: 300,
      fromPrice: true,
      headroom: 'Low headroom configuration',
      trackNote: 'Bi-parting — doors slide APART',
      description: 'The Baltimore is our double bi-parting low headroom barn door hardware kit. Combines the opening style of the Brooklyn with a compact headroom requirement. UK manufactured in Cardiff.',
      features: [
        'UK manufactured in Cardiff',
        'Bi-parting — doors slide apart from centre',
        'Low headroom configuration',
        'Double door system',
        'Ideal for wide openings with restricted ceiling height',
        'All fixings included',
      ],
      image: '/img/baltimore-system.jpg',
      images: ['/img/baltimore-system.jpg'],
      buyLink: 'https://www.barn-doors.co.uk/?Page_ID=3610&id=975411',
      badge: 'LOW HEADROOM',
      category: 'barn-door-hardware',
      metaTitle: 'Baltimore Double Bi-Parting Low Headroom Barn Door Hardware | DoorMate',
      metaDesc: 'Baltimore double bi-parting low headroom barn door kit. Doors slide apart. UK manufactured Cardiff. From £300. Wide openings, tight ceilings.',
    },
    {
      slug: 'covington',
      name: 'Covington',
      type: 'Single Track Bi-Passing',
      price: 375,
      fromPrice: true,
      headroom: 'Standard headroom',
      trackNote: 'Single track — doors PASS each other',
      description: 'The Covington is our single track bi-passing barn door hardware system. Both doors run on the same track and pass each other — one slides left, one slides right. UK manufactured in Cardiff.',
      features: [
        'UK manufactured in Cardiff',
        'Bi-passing — doors pass each other on a single track',
        'Doors stack at either side when open',
        'Single track system',
        'All fixings included',
        'Soft close available separately',
      ],
      image: '/img/covington-system.jpg',
      images: ['/img/covington-system.jpg', '/img/covington-system-2.jpg'],
      buyLink: 'https://www.barn-doors.co.uk/?Page_ID=3610&id=754352',
      badge: 'BI-PASSING',
      category: 'barn-door-hardware',
      metaTitle: 'Covington Single Track Bi-Passing Barn Door Hardware | From £375 | DoorMate',
      metaDesc: 'Covington single track bi-passing barn door hardware. Doors pass each other on one track. UK manufactured Cardiff. From £375.',
    },
    {
      slug: 'augusta',
      name: 'Augusta',
      type: 'Double Track Bi-Passing',
      price: 395,
      fromPrice: true,
      headroom: 'Standard 315mm / Reversed 229mm',
      trackNote: 'Two parallel tracks — doors PASS each other',
      description: 'The Augusta is our double track bi-passing barn door hardware system. Two tracks run parallel — each door has its own track. When you need two parallel tracks, it\'s always the Augusta. UK manufactured in Cardiff.',
      features: [
        'UK manufactured in Cardiff',
        'Two parallel tracks — one per door',
        'Standard headroom: 315mm',
        'Reversed headroom: 229mm',
        'Doors pass each other independently',
        'All fixings included',
      ],
      image: '/img/augusta-system.jpg',
      images: ['/img/augusta-system.jpg', '/img/augusta-system-2.jpg'],
      buyLink: 'https://www.barn-doors.co.uk/?Page_ID=3610&id=754357',
      badge: 'DOUBLE TRACK',
      category: 'barn-door-hardware',
      metaTitle: 'Augusta Double Track Bi-Passing Barn Door Hardware | From £395 | DoorMate',
      metaDesc: 'Augusta double track bi-passing barn door hardware. Two parallel tracks, one per door. Standard 315mm / reversed 229mm headroom. UK made. From £395.',
    },
  ],

  'pocket-door-kits': [
    {
      slug: 'coburn',
      name: 'Coburn Pocket Door Kit',
      type: 'Pocket Door Kit',
      price: 117.60,
      fromPrice: false,
      description: 'The Coburn is our entry-level pocket door kit. Reliable, simple to install, and suitable for standard internal doors. The door slides completely into the wall cavity when open. For double doors, add quantity 2 to basket.',
      features: [
        'Complete pocket door kit',
        'Suitable for standard internal doors',
        'Door disappears completely into wall',
        'Simple installation',
        'All fixings included',
        'For double doors: add qty 2',
      ],
      image: '/img/coburn-kit.jpg',
      images: ['/img/coburn-kit.jpg'],
      buyLink: null,
      badge: null,
      subtitle: 'For Double Doors Add Qty 2 To Basket',
      category: 'pocket-door-kits',
      metaTitle: 'Coburn Pocket Door Kit | £117.60 | DoorMate Cardiff',
      metaDesc: 'Coburn pocket door kit. Door slides completely into the wall. £117.60. For double doors add qty 2. Buy from DoorMate, the UK\'s sliding door specialists.',
    },
    {
      slug: 'rocket',
      name: 'Rocket Pocket Door Kit',
      type: 'Pocket Door Kit',
      price: 167.94,
      fromPrice: false,
      description: 'The Rocket pocket door kit offers a step up in quality and load capacity. Ideal for heavier internal doors. The door slides cleanly into the wall cavity. For double doors, add quantity 2 to basket.',
      features: [
        'Higher load capacity than Coburn',
        'Suitable for heavier internal doors',
        'Door disappears completely into wall',
        'Clean, reliable mechanism',
        'All fixings included',
        'For double doors: add qty 2',
      ],
      image: '/img/rocket-kit.jpg',
      images: ['/img/rocket-kit.jpg'],
      buyLink: null,
      badge: null,
      subtitle: 'For Double Doors Add Qty 2 To Basket',
      category: 'pocket-door-kits',
      metaTitle: 'Rocket Pocket Door Kit | £167.94 | DoorMate Cardiff',
      metaDesc: 'Rocket pocket door kit. Higher load capacity. £167.94. For double doors add qty 2. DoorMate — the UK\'s only mirror pocket door manufacturer.',
    },
    {
      slug: 'eclisse',
      name: 'Eclisse Pocket Door Kit',
      type: 'Pocket Door Kit',
      price: 304.80,
      fromPrice: false,
      description: 'The Eclisse is our premium pocket door kit. Engineered for precision, smooth operation and longevity. Suitable for high-specification interiors. For double doors, add quantity 2 to basket.',
      features: [
        'Premium quality pocket door kit',
        'Precision-engineered mechanism',
        'Smooth, silent operation',
        'High-specification interiors',
        'All fixings included',
        'For double doors: add qty 2',
      ],
      image: '/img/eclisse-kit.jpg',
      images: ['/img/eclisse-kit.jpg'],
      buyLink: null,
      badge: 'PREMIUM',
      subtitle: 'For Double Doors Add Qty 2 To Basket',
      category: 'pocket-door-kits',
      metaTitle: 'Eclisse Pocket Door Kit | £304.80 | DoorMate Cardiff',
      metaDesc: 'Eclisse premium pocket door kit. £304.80. Precision-engineered for high-spec interiors. DoorMate — Cardiff\'s sliding door specialists.',
    },
    {
      slug: 'mirror-single-pocket-door',
      name: 'Mirror Single Pocket Door',
      type: 'Mirror Pocket Door',
      price: 395,
      fromPrice: false,
      leadTime: '2–3 weeks',
      description: 'DoorMate is the only UK manufacturer of mirror pocket doors. Our single mirror pocket door transforms hallways and living spaces — the door slides into the wall and the mirror creates the illusion of space. Made to order. 2–3 week lead time.',
      features: [
        'Only UK manufacturer of mirror pocket doors',
        'Single mirror pocket door',
        'Door slides fully into wall cavity',
        'Creates illusion of space',
        'Made to order — 2–3 week lead time',
        'We recommend 30–45kg soft close (sold separately)',
      ],
      image: '/img/mirror-pocket-single.jpg',
      images: ['/img/mirror-pocket-single.jpg'],
      buyLink: 'https://www.barn-doors.co.uk/?Page_ID=3610&id=1275641',
      badge: 'ONLY UK MAKER',
      category: 'pocket-door-kits',
      metaTitle: 'Mirror Single Pocket Door | £395 | Only UK Manufacturer | DoorMate',
      metaDesc: 'DoorMate is the only UK manufacturer of mirror pocket doors. Single mirror pocket door £395. Made to order, 2–3 week lead time. Cardiff.',
    },
    {
      slug: 'mirror-double-pocket-door',
      name: 'Mirror Double Pocket Door',
      type: 'Mirror Pocket Door',
      price: 790,
      fromPrice: false,
      leadTime: '2–3 weeks',
      description: 'DoorMate is the only UK manufacturer of mirror pocket doors. Our double mirror pocket door is a statement piece — two doors slide apart into opposing wall cavities revealing a full mirror on each. Made to order. 2–3 week lead time.',
      features: [
        'Only UK manufacturer of mirror pocket doors',
        'Double mirror pocket door',
        'Two doors slide apart into wall cavities',
        'Full mirror on each door panel',
        'Made to order — 2–3 week lead time',
        'We recommend 30–45kg soft close (sold separately)',
      ],
      image: '/img/mirror-pocket-2.jpg',
      images: ['/img/mirror-pocket-2.jpg'],
      buyLink: 'https://www.barn-doors.co.uk/?Page_ID=3610&id=1275642',
      badge: 'ONLY UK MAKER',
      category: 'pocket-door-kits',
      metaTitle: 'Mirror Double Pocket Door | £790 | Only UK Manufacturer | DoorMate',
      metaDesc: 'DoorMate is the only UK manufacturer of mirror double pocket doors. £790. Two mirror doors slide apart. Made to order. 2–3 weeks. Cardiff.',
    },
  ],

  'doors': [
    {
      slug: 'pine-single-barn-door',
      name: 'Pine Single Barn Door',
      type: 'Handmade in Cardiff',
      price: 527,
      fromPrice: true,
      description: 'Our handmade pine single barn doors are crafted to your exact dimensions in our Cardiff workshop. Available in V-Brace, Z-Brace, Ledge and Brace, and Glazed panel designs. Each door is unique — made for your space, your wall, your home. Sliding hardware sold separately.',
      features: [
        'Handmade in Cardiff to your dimensions',
        'Solid pine construction',
        'V-Brace, Z-Brace, Ledge and Brace, Glazed panel designs',
        'Hardware sold separately — we advise the right kit',
        'Oak available — price on application',
      ],
      image: '/img/door-v-brace.jpg',
      images: ['/img/door-v-brace.jpg', '/img/door-double-z-brace.jpg', '/img/door-z-brace-mirror.jpg'],
      buyLink: null,
      contactForPrice: true,
      badge: 'HANDMADE',
      category: 'doors',
      metaTitle: 'Handmade Pine Single Barn Door | From £527 | Made in Cardiff | DoorMate',
      metaDesc: 'Handmade pine single barn doors from £527. Made to your exact dimensions in Cardiff. V-Brace, Z-Brace, Ledge and Brace, Glazed panel. DoorMate.',
    },
    {
      slug: 'pine-double-barn-door',
      name: 'Pine Double Barn Door',
      type: 'Handmade in Cardiff',
      price: 1146,
      fromPrice: true,
      description: 'Our handmade pine double barn doors are built as a matching pair to your exact dimensions in our Cardiff workshop. Perfect for wide openings. Available in V-Brace, Z-Brace, Ledge and Brace, and Glazed panel designs. Sliding hardware sold separately.',
      features: [
        'Handmade in Cardiff to your dimensions',
        'Matching pair, solid pine',
        'V-Brace, Z-Brace, Ledge and Brace, Glazed panel designs',
        'Perfect for bi-parting or bi-passing hardware systems',
        'Hardware sold separately — we advise the right kit',
        'Oak available — price on application',
      ],
      image: '/img/door-double-z-brace.jpg',
      images: ['/img/door-double-z-brace.jpg', '/img/door-v-brace.jpg'],
      buyLink: null,
      contactForPrice: true,
      badge: 'HANDMADE',
      category: 'doors',
      metaTitle: 'Handmade Pine Double Barn Door | From £1,146 | Made in Cardiff | DoorMate',
      metaDesc: 'Handmade pine double barn doors from £1,146. Matching pair made to size in Cardiff. V-Brace, Z-Brace, Ledge and Brace or Glazed. DoorMate.',
    },
  ],

  'external-sliding-kits': [
    {
      slug: 'dm-75',
      name: 'DM-75 External Sliding Kit',
      type: 'External Sliding Kit',
      price: 104,
      fromPrice: false,
      capacity: '75kg',
      description: 'The DM-75 external sliding door kit handles doors up to 75kg. Designed for outbuildings, garages, sheds and agricultural buildings. Weather-resistant construction. Suitable for timber or steel doors.',
      features: [
        'Maximum door weight: 75kg',
        'Designed for external use',
        'Outbuildings, garages, sheds',
        'Weather-resistant construction',
        'Suitable for timber or steel doors',
        'All fixings included',
      ],
      image: '/img/dm-75.jpg',
      images: ['/img/dm-75.jpg'],
      buyLink: null,
      badge: '75KG',
      category: 'external-sliding-kits',
      metaTitle: 'DM-75 External Sliding Door Kit 75kg | £104 | DoorMate',
      metaDesc: 'DM-75 external sliding door kit. 75kg capacity. For outbuildings, garages and sheds. £104. DoorMate — the UK\'s sliding door specialists.',
    },
    {
      slug: 'dm-100',
      name: 'DM-100 External Sliding Kit',
      type: 'External Sliding Kit',
      price: 156,
      fromPrice: false,
      capacity: '100kg',
      description: 'The DM-100 external sliding door kit handles doors up to 100kg. A step up in capacity for heavier external doors. Designed for outbuildings, garages and agricultural buildings. Weather-resistant construction.',
      features: [
        'Maximum door weight: 100kg',
        'Designed for external use',
        'Outbuildings, garages, agricultural buildings',
        'Weather-resistant construction',
        'Suitable for heavy timber or steel doors',
        'All fixings included',
      ],
      image: '/img/external-kit.jpg',
      images: ['/img/external-kit.jpg'],
      buyLink: null,
      badge: '100KG',
      category: 'external-sliding-kits',
      metaTitle: 'DM-100 External Sliding Door Kit 100kg | £156 | DoorMate',
      metaDesc: 'DM-100 external sliding door kit. 100kg capacity. For outbuildings, garages. £156. DoorMate — Cardiff\'s sliding door specialists.',
    },
    {
      slug: 'dm-150',
      name: 'DM-150 External Sliding Kit',
      type: 'External Sliding Kit',
      price: 229,
      fromPrice: false,
      capacity: '150kg',
      description: 'The DM-150 external sliding door kit handles doors up to 150kg. Built for large, heavy external sliding doors on farm buildings, workshops and large garages. Weather-resistant construction.',
      features: [
        'Maximum door weight: 150kg',
        'Designed for external use',
        'Farms, workshops, large garages',
        'Weather-resistant construction',
        'Heavy-duty hardware',
        'All fixings included',
      ],
      image: '/img/dm-150.jpg',
      images: ['/img/dm-150.jpg'],
      buyLink: null,
      badge: '150KG',
      category: 'external-sliding-kits',
      metaTitle: 'DM-150 External Sliding Door Kit 150kg | £229 | DoorMate',
      metaDesc: 'DM-150 external sliding door kit. 150kg capacity. For large farm buildings, workshops and garages. £229. DoorMate.',
    },
    {
      slug: 'dm-200',
      name: 'DM-200 External Sliding Kit',
      type: 'External Sliding Kit',
      price: 281,
      fromPrice: false,
      capacity: '200kg',
      description: 'The DM-200 is our heaviest external sliding door kit, handling doors up to 200kg. Built for the most demanding external applications — large agricultural buildings, industrial units and double-width barn doors.',
      features: [
        'Maximum door weight: 200kg',
        'Designed for external use',
        'Agricultural buildings, industrial units',
        'Heaviest-duty hardware in our external range',
        'Weather-resistant construction',
        'All fixings included',
      ],
      image: '/img/external-kit.jpg',
      images: ['/img/external-kit.jpg'],
      buyLink: null,
      badge: '200KG',
      category: 'external-sliding-kits',
      metaTitle: 'DM-200 External Sliding Door Kit 200kg | £281 | DoorMate',
      metaDesc: 'DM-200 external sliding door kit. 200kg capacity. For large agricultural and industrial buildings. £281. DoorMate.',
    },
  ],
}

export const ALL_PRODUCTS = Object.values(PRODUCTS).flat()

export const CATEGORIES = [
  {
    slug: 'doors',
    name: 'Doors',
    label: 'HANDMADE IN CARDIFF',
    description: 'Handmade pine barn doors built to your exact dimensions in our Cardiff workshop.',
    image: '/img/door-v-brace.jpg',
    priceFrom: 'from £527',
  },
  {
    slug: 'barn-door-hardware',
    name: 'Barn Door Hardware',
    label: 'UK MANUFACTURED',
    description: 'The UK\'s only bespoke barn door hardware manufacturer. Every system made in Cardiff since 2009.',
    image: '/img/gainesville-system.jpg',
    priceFrom: 'from £150',
  },
  {
    slug: 'pocket-door-kits',
    name: 'Pocket Door Kits',
    label: 'ONLY UK MIRROR MAKER',
    description: 'From the Coburn entry kit to our unique mirror pocket doors — the only UK manufacturer.',
    image: '/img/coburn-kit.jpg',
    priceFrom: 'from £117.60',
  },
  {
    slug: 'internal-sliding-kits',
    name: 'Internal Sliding Door Kits',
    label: 'COMING SOON',
    description: 'Internal aluminium and stainless steel sliding door systems. Coming soon.',
    image: '/img/hero-installed.jpg',
    priceFrom: null,
  },
  {
    slug: 'external-sliding-kits',
    name: 'External Sliding Door Kits',
    label: 'OUTBUILDINGS & GARAGES',
    description: 'Heavy-duty external sliding kits from 75kg to 200kg capacity. For garages, barns and outbuildings.',
    image: '/img/dm-75.jpg',
    priceFrom: 'from £104',
  },
  {
    slug: 'gallery',
    name: 'Gallery',
    label: 'REAL INSTALLATIONS',
    description: 'Real DoorMate installations across the UK — from Cardiff homes to Channel 4 TV.',
    image: '/img/hero-installed.jpg',
    priceFrom: null,
  },
]

export function formatPrice(product) {
  const formatted = product.price % 1 === 0
    ? `£${product.price.toLocaleString()}.00`
    : `£${product.price.toFixed(2)}`
  return product.fromPrice ? `from ${formatted}` : formatted
}
